In [ ]:
import importlib

In [ ]:
import models_tf
importlib.reload(models_tf)

In [ ]:
import tensorflow as tf
import numpy as np
import os

In [ ]:
model,x,y = models_tf.avg1d(32)

In [ ]:
logdir='/home/ubuntu/tf_logs'
os.system('rm -rf {}'.format(logdir))

with tf.profiler.experimental.Profile(logdir):
    model.fit(x, y, batch_size = 64,
            epochs=1)
    pass

In [ ]:
# import numpy as np

# arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

# arr

# np.mean(arr,axis=2)

In [ ]:
from funs import dataset

In [ ]:
x,y,input_shape = dataset(dim=2)

In [2]:
import torch

In [3]:

a = torch.zeros(4, 4)
print(a)
# tensor([[0., 0., 0., 0.],
#         [0., 0., 0., 0.],
#         [0., 0., 0., 0.],
#         [0., 0., 0., 0.]])
b = a.view(16,)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [6]:
a.view(-1,1)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])